{% set version = "2.5.2" %}

package:
  name: cadquery
  version: {{ version }}

source:
  url: https://github.com/CadQuery/cadquery/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7503a18c411bf4ed7915f7bdb72bc01eec53ebe89fac358695dfc26053e0f99f

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - casadi
    - ezdxf >=1.3.0
    - ipython
    - multimethod >=1.11,<2
    - nlopt
    - ocp 7.7.2
    - pyparsing >=2.1.9
    - python >={{ python_min }}
    - typing_extensions
    - typish
    - vtk =*=qt*

test:
  requires:
    - docutils
    - mypy
    - path
    - pip
    - pytest
    - pytest-cov
    - python {{ python_min }}
  source_files:
    - tests
  imports:
    - cadquery
  commands:
    - pip check
    - mypy -m cadquery
    - coverage run --source=cadquery --branch -m pytest -vv --tb=long --color=yes -k "not (constraint_validation or constraint_solver)"
    - coverage report --show-missing --skip-covered --fail-under=90

about:
  home: https://github.com/cadquery/cadquery
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    CadQuery is a parametric scripting language for creating and traversing
    CAD models
  description: |
    CadQuery is an intuitive, easy-to-use python library for building
    parametric 3D CAD models. It has several goals:
    - Build models with scripts that are as close as possible to how you’d
      describe the object to a human, using a standard, already established
      programming language
    - Create parametric models that can be very easily customized by end users
    - Output high quality CAD formats like STEP and AMF in addition to
      traditional STL
    - Provide a non-proprietary, plain text model format that can be edited and
      executed with only a web browser
  doc_url: https://cadquery.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - adam-urbanczyk
