# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.6.1"

package:
  name: cadquery
  version: ${{ version }}

source:
  url: https://github.com/CadQuery/cadquery/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 8cd6b4c7c06529b38a76c62b0ea09e209f2d2a698cf81d7e9221a3e9f03f6d35

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - casadi
    - ezdxf >=1.3.0
    - ipython
    - multimethod >=1.11,<2
    - nlopt >=2.9.0,<3.0
    - path
    - ocp >=7.8.1,<7.9
    - python >=${{ python_min }}
    - trame
    - trame-vtk
    - typish

tests:
  - python:
      imports: cadquery
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - tests
    requirements:
      run:
        - docutils
        - mypy
        - path
        - pip
        - pytest
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - pip check
      - mypy -m cadquery
      - coverage run --source=cadquery --branch -m pytest -vv --tb=long --color=yes -k "not (constraint_validation or constraint_solver)"
      - coverage report --show-missing --skip-covered --fail-under=90

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    CadQuery is a parametric scripting language for creating and traversing
    CAD models
  description: |
    CadQuery is an intuitive, easy-to-use python library for building
    parametric 3D CAD models. It has several goals:
    - Build models with scripts that are as close as possible to how you’d
    describe the object to a human, using a standard, already established
    programming language
    - Create parametric models that can be very easily customized by end users
    - Output high quality CAD formats like STEP and AMF in addition to
    traditional STL
    - Provide a non-proprietary, plain text model format that can be edited and
    executed with only a web browser
  homepage: https://github.com/cadquery/cadquery
  documentation: https://cadquery.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - adam-urbanczyk
